In [1]:
import numpy as np
from sklearn.model_selection import TimeSeriesSplit

In [5]:
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4]])
Y = np.array([1, 2, 3, 4])

In [22]:
tscv = TimeSeriesSplit(n_splits=2)
tscv

TimeSeriesSplit(gap=0, max_train_size=None, n_splits=2, test_size=None)

In [23]:
for i, j in tscv.split(X,Y):
    print("TRAIN:", i, "TEST:", j)
    X_train,X_test = X[i],X[j]
    Y_train,Y_test = Y[i],Y[j]

TRAIN: [0 1] TEST: [2]
TRAIN: [0 1 2] TEST: [3]


In [12]:
X_train

array([[1, 2],
       [3, 4],
       [1, 2]])

In [13]:
X_test

array([[3, 4]])

In [14]:
Y_train

array([1, 2, 3])

In [15]:
Y_test

array([4])

In [18]:
tscv_3 = TimeSeriesSplit(n_splits=3)
tscv_3

TimeSeriesSplit(gap=0, max_train_size=None, n_splits=3, test_size=None)

In [20]:
for i, j in tscv_3.split(X,Y):
    
    print("TRAIN:", i, "TEST:", j)
    X_train,X_test = X[i],X[j]
    Y_train,Y_test = Y[i],Y[j]

print('X_train:',X_train)
print('X_test:',X_test)
print('Y_train:',Y_train)
print('Y_test:',Y_test)

TRAIN: [0] TEST: [1]
TRAIN: [0 1] TEST: [2]
TRAIN: [0 1 2] TEST: [3]
X_train: [[1 2]
 [3 4]
 [1 2]]
X_test: [[3 4]]
Y_train: [1 2 3]
Y_test: [4]
